### ISSUE TITLE
Get messages from comments 

### ISSUE THREAD

**Issue by deedos** [LUKKIEN/wagtailsocialfeed#14]
Hi. In #13 you instructed how to get retrieve additional data and I 'm trying here:
My goal is to get all the comments from a given post in the moderate view.
I 'm tryng inside "from_raw" method :
```
messages = []
        
        if 'comments' in raw:
            for x in raw['comments']['data']:
                messages.append(x['message'])
        mensagens = {el for el in messages}      
        print (mensagens)
        
```
and add to the cls return:

```
return cls(
comments=mensagens, )
```

I succesful print a dict with all the comments from the posts retrieved. I 'm having troubles to view those in the moderate page. I 'm tryng right under https://github.com/LUKKIEN/wagtailsocialfeed/blob/master/wagtailsocialfeed/templates/wagtailsocialfeed/admin/moderate.html#L51 :+1: 

```
                {% for item in post.comments %}
                    <li>{{ item }}</li>
                {% endfor %}
```

nothing happens.
could you help me to achieve this ?
cheers

**Comment by tleguijt** [comment]
If you return a `FeedItem` like you demonstrated with your code, the FeedItem will be missing all of the other required information.
The current attributes that are being passed on to the FeedItem are;

```
return cls(
            id=raw['id'],
            type='facebook',
            text=item_type.get_text_from(raw),
            image_dict=image,
            posted=cls.get_post_date(raw),
            original_data=raw,
        )
```

Before you return the new FeedItem, you could set extra attributes and then return it.
Or, as all the original information is still available via `FeedItem`.`original_data`, in your template code you could do something like:

```
{% for comment_data in post.original_data.comments.data %}
   <li>{{ comment_data.message }}</li>
{% endfor %}
```
